INSERT INTO CATEGORIA (NOMCAT, ESTCAT) VALUES ('Gaseosas', 'A');
INSERT INTO CATEGORIA (NOMCAT, ESTCAT) VALUES ('Chocolates', 'A');
INSERT INTO CATEGORIA (NOMCAT, ESTCAT) VALUES ('Snacks', 'A');
INSERT INTO CATEGORIA (NOMCAT, ESTCAT) VALUES ('Dulces', 'A');
INSERT INTO CATEGORIA (NOMCAT, ESTCAT) VALUES ('Galletas', 'A');