INSERT INTO PRODUCTO (NOMPROD,PREPROD,IDCAT,ESTPROD) VALUES ('Pato de hule',51,1,'A');
INSERT INTO PRODUCTO (NOMPROD,PREPROD,IDCAT,ESTPROD) VALUES ('iPhone xs',42,2,'A');
INSERT INTO PRODUCTO (NOMPROD,PREPROD,IDCAT,ESTPROD) VALUES ('Gi pi es',33,1,'A');
INSERT INTO PRODUCTO (NOMPROD,PREPROD,IDCAT,ESTPROD) VALUES ('Jet Ski',24,1,'A');
INSERT INTO PRODUCTO (NOMPROD,PREPROD,IDCAT,ESTPROD) VALUES ('Cuy magico',15,1,'A');